### ISSUE TITLE
I set it up like this, but what should I do if it still fails?

### ISSUE THREAD

**Issue by teabagging** [daviardev/you-short#1]
Hello
o?name=videos%2FY2meta.app-Mr.%20K%20With%20The%20…%20%23shorts%20%23changgang%20%23gtarp-(480p).mp4 | CORS 错误 | xhr | 813-fad06ec6e8657cc0.js:412 | 0 B | 722 毫秒
o?name=videos%2FY2meta.app-Mr.%20K%20With%20The%20…%20%23shorts%20%23changgang%20%23gtarp-(480p).mp4 | 404 | preflight | 预检

The easiest way to configure your data for CORS is with the gsutil command line tool. The installation instructions for gsutil are available at https://cloud.google.com/storage/docs/gsutil_install. Once you've installed gsutil and authenticated with it, you can use it to configure CORS. For example, if you just want to allow object downloads from your custom domain, put this data in a file named cors.json (replacing "https://example.com" with your domain ): [ { "origin": ["https://example.com"], "method": ["GET"], "maxAgeSeconds": 3600 } ] Then, run this command (replacing "exampleproject.appspot.com " with the name of your bucket): gsutil cors set cors.json gs://exampleproject.appspot.com 

I set it up like this, but what should I do if it still fails?

**Comment by daviardev** [comment]
I don't have a clear answer, since I only did the project for learning purposes, and I didn't see the need to add security, but I appreciate what you are doing.
